Models/ThuongHieu.cs
namespace ngay8thang3_Complete.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("ThuongHieu")]
    public partial class ThuongHieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThuongHieu()
        {
            DongHo = new HashSet<DongHo>();
        }

        public int ID { get; set; }

        [Required]
        [StringLength(255)]
        public string TenThuongHieu { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DongHo> DongHo { get; set; }
    }
}

Controllers/DongHoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ngay8thang3_Complete.Models;
using PagedList;

namespace ngay8thang3_Complete.Controllers
{
    public class DongHoesController : Controller
    {
        private MyShopDbContext db = new MyShopDbContext();
        [ChildActionOnly]
        // GET: DongHoes
        //danh mục thể loại
        public ActionResult Category()
        {
            var catego = db.LoaiDHs.ToList();
            return PartialView(catego);
        }

        public ActionResult ListId(int ID)
        {
            var list = db.DongHoes.Where(d => d.TenLoai_ID == ID).ToList();
            return View(list);

        }
        //thương hiệu
        public ActionResult ThuongHieu()
        {
            var th = db.ThuongHieux.OrderBy(d => d.ID).ToList();
            return PartialView(th);
        }
        public ActionResult list_th(int id)
        {
            var th = db.DongHoes.Where(d => d.ThuongHieu_ID == id).ToList();
            return View(th);
        }
        //danh sách
        //Danh sách 1
        //public ActionResult Index(string SearchString)
        //{
        //    if (SearchString != null)
        //    {
        //        var dh = db.DongHoes.Where(x => x.TenDongHo.Contains(SearchString));
        //        Session["search"] = SearchString;
        //        return View(dh.ToList());
        //    }
        //    else
        //    {
        //        var dh = db.DongHoes;
        //        Session["search"] = null;
        //        return View(dh.ToList());
        //    }

           
        //}
        //dùng tay để phân trang, tìm kiếm và sắp xếp
        public ActionResult Index(string currentFilter, string SearchString, int? page)
        {
            var dongho = new List<DongHo>();
            if (SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = currentFilter;
            }
            if (!string.IsNullOrEmpty(SearchString))
            {
                //lấy ds sản phẩm theo từ khóa tìm kiếm
                dongho = db.DongHoes.Where(n => n.TenDongHo.Contains(SearchString)).ToList();
                Session["search"] = SearchString;
            }
            else
            {
                //lay all sån phâm trong bång product
                dongho = db.DongHoes.ToList();
                Session["search"] = null; ;
            }
            ViewBag.CurrentFilter = SearchString;
            //số lượng item của 1 trang = 4
            int pageSize = 12;
            int pageNumber = (page ?? 1);
            if (dongho.ToList().Count<1)
            {
                ViewBag.thongbao = "Hiện tại không có sản phẩm nào";
            }
            
            //sắp xếp theo id sản phẩm,sp mới đưa lên đầu
            dongho = dongho.OrderByDescending(n => n.ID).ToList();
            return View(dongho.ToPagedList(pageNumber, pageSize));

        }
        //kết thúc danh sách 1
        //danh sách 2
        public ActionResult Index2()
        {
            var List = db.DongHoes.Include(d => d.ChatLieu).Include(d => d.LoaiDH).Include(d => d.ThuongHieu).Include(d => d.XuatXu);
            return View(List.ToList());
        }
        // GET: DongHoes/Details/5
        public ActionResult Details(int? id)
        {
            var dt = db.DongHoes.Where(d => d.ID == id).SingleOrDefault();
            return View(dt);
        }
        public ActionResult Detailsss(int? id)
        {
            var dt = db.DongHoes.Where(d => d.ID == id).SingleOrDefault();
            return View(dt);
        }

        // GET: DongHoes/Create
        public ActionResult Create()
        {
            ViewBag.ChatLieu_ID = new SelectList(db.ChatLieux, "ID", "TenChatLieu");
            ViewBag.TenLoai_ID = new SelectList(db.LoaiDHs, "ID", "TenLoai");
            ViewBag.ThuongHieu_ID = new SelectList(db.ThuongHieux, "ID", "TenThuongHieu");
            ViewBag.XuatXu_ID = new SelectList(db.XuatXus, "ID", "TenQG");
            return View();
        }

        // POST: DongHoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ThuongHieu_ID,TenLoai_ID,ChatLieu_ID,XuatXu_ID,TenDongHo,MauSac,HanBaoHanh,DonGia,SoLuong,HinhAnhDH,MoTa")] DongHo dongHo)
        {
            if (ModelState.IsValid)
            {
                db.DongHoes.Add(dongHo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ChatLieu_ID = new SelectList(db.ChatLieux, "ID", "TenChatLieu", dongHo.ChatLieu_ID);
            ViewBag.TenLoai_ID = new SelectList(db.LoaiDHs, "ID", "TenLoai", dongHo.TenLoai_ID);
            ViewBag.ThuongHieu_ID = new SelectList(db.ThuongHieux, "ID", "TenThuongHieu", dongHo.ThuongHieu_ID);
            ViewBag.XuatXu_ID = new SelectList(db.XuatXus, "ID", "TenQG", dongHo.XuatXu_ID);
            return View(dongHo);
        }

        // GET: DongHoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DongHo dongHo = db.DongHoes.Find(id);
            if (dongHo == null)
            {
                return HttpNotFound();
            }
            ViewBag.ChatLieu_ID = new SelectList(db.ChatLieux, "ID", "TenChatLieu", dongHo.ChatLieu_ID);
            ViewBag.TenLoai_ID = new SelectList(db.LoaiDHs, "ID", "TenLoai", dongHo.TenLoai_ID);
            ViewBag.ThuongHieu_ID = new SelectList(db.ThuongHieux, "ID", "TenThuongHieu", dongHo.ThuongHieu_ID);
            ViewBag.XuatXu_ID = new SelectList(db.XuatXus, "ID", "TenQG", dongHo.XuatXu_ID);
            return View(dongHo);
        }

        // POST: DongHoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ThuongHieu_ID,TenLoai_ID,ChatLieu_ID,XuatXu_ID,TenDongHo,MauSac,HanBaoHanh,DonGia,SoLuong,HinhAnhDH,MoTa")] DongHo dongHo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dongHo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ChatLieu_ID = new SelectList(db.ChatLieux, "ID", "TenChatLieu", dongHo.ChatLieu_ID);
            ViewBag.TenLoai_ID = new SelectList(db.LoaiDHs, "ID", "TenLoai", dongHo.TenLoai_ID);
            ViewBag.ThuongHieu_ID = new SelectList(db.ThuongHieux, "ID", "TenThuongHieu", dongHo.ThuongHieu_ID);
            ViewBag.XuatXu_ID = new SelectList(db.XuatXus, "ID", "TenQG", dongHo.XuatXu_ID);
            return View(dongHo);
        }

        // GET: DongHoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DongHo dongHo = db.DongHoes.Find(id);
            if (dongHo == null)
            {
                return HttpNotFound();
            }
            return View(dongHo);
        }

        // POST: DongHoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DongHo dongHo = db.DongHoes.Find(id);
            db.DongHoes.Remove(dongHo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        /// <summary>
        /// Khhuyeens mại
        /// </summary>
        public PartialViewResult KhuyenMai()
        {
            var km = from dh in db.DongHoes
                     where dh.KhuyenMai > 0
                     select dh;
            return PartialView("_KhuyenMai", km);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/ShoppingCardController.cs
using ngay8thang3_Complete.Models;
using ngay8thang3_Complete.Models.CommonModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ngay8thang3_Complete.Controllers
{
    public class ShoppingCardController : Controller
    {
        // GET: ShoppingCard
        MyShopDbContext db = new MyShopDbContext();
        public ActionResult Index()
        {
            if(TempData["thongbao"]!= null)
            {
                ViewBag.tb = TempData["thongbao"];
            }    
            return View();
        }
        public ActionResult ThemVaoGio(int maSP)
        {
            if (Session["cart"] == null)
            {
                var sp = db.DongHoes.Find(maSP);
                List<CartItem> cart = new List<CartItem>();
                cart.Add(new CartItem { dongho = sp, soLuongTrongGio = 1 });
                Session["cart"] = cart;
                Session["count"] = 1;
            }
            else
            {
                List<CartItem> cart = (List<CartItem>)Session["cart"];
                
                int index = isExist(maSP);
                if (index != -1)
                {
                    cart[index].soLuongTrongGio++;
                }
                else
                {
                    var sp = db.DongHoes.Find(maSP);
                    cart.Add(new CartItem { dongho = sp, soLuongTrongGio = 1 });
                    Session["count"] = Convert.ToInt32(Session["count"]) + 1;
                }
                Session["cart"] = cart;
            }

            return RedirectToAction("Index");
        }

        // GET: GioHang/CapNhatTang/{maSP}
        public ActionResult CapNhatTang(int maSP)
        {
            var sp = db.DongHoes.Find(maSP);
            List<CartItem> cart = (List<CartItem>)Session["cart"];
            foreach (var item in cart)
            {
                if (item.dongho.ID == maSP && item.soLuongTrongGio <= 10)
                    if (item.soLuongTrongGio < sp.SoLuong)
                    {
                        item.soLuongTrongGio++;
                    }
                    else
                    {
                        TempData["Message"] = "Sản phẩm không đủ số lượng hiện có " + sp.SoLuong;
                    }

            }
            Session["cart"] = cart;

            return RedirectToAction("Index");
        }

        // GET: GioHang/CapNhatGiam/{maSP}
        public ActionResult CapNhatGiam(int maSP)
        {
            List<CartItem> cart = (List<CartItem>)Session["cart"];
            foreach (var item in cart)
            {
                if (item.dongho.ID == maSP && item.soLuongTrongGio >= 1)
                    item.soLuongTrongGio--;
            }
            Session["cart"] = cart;

            return RedirectToAction("Index");
        }

        // GET: GioHang/XoaKhoiGio/{maSP}
        public ActionResult XoaKhoiGio(int maSP)
        {
            List<CartItem> cart = (List<CartItem>)Session["cart"];
            int index = isExist(maSP);
            cart.RemoveAt(index);
            Session["cart"] = cart;
            Session["count"] = Convert.ToInt32(Session["count"]) - 1;
            return RedirectToAction("Index");
        }

        private int isExist(int id)
        {
            List<CartItem> cart = (List<CartItem>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].dongho.ID.Equals(id))
                    return i;
            return -1;
        }
        //thanh toán
        public ActionResult ThanhToan()
        {
            if (Session["iduser"] == null)
            {
                return RedirectToAction("Index", "KhachHangs");
            }
            else
            {
                return View();
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ThanhToan(DatHang datHang)
        {
            if (ModelState.IsValid)
            {
                // Lưu vào bảng DatHang
                DatHang dh = new DatHang();
                dh.DiaChiGiaoHang = datHang.DiaChiGiaoHang;
                dh.DienThoaiGiaoHang = datHang.DienThoaiGiaoHang;
                dh.NgayDatHang = DateTime.Now;
                dh.KhachHang_ID = Convert.ToInt32(Session["iduser"]);
                dh.TinhTrang = 0;
                db.DatHangs.Add(dh);
                db.SaveChanges();

                // Lưu vào bảng DatHang_ChiTiet
                List<CartItem> cart = (List<CartItem>)Session["cart"];
                foreach (var item in cart)
                {
                    DatHang_ChiTiet ct = new DatHang_ChiTiet();
                    ct.DatHang_ID = dh.ID;
                    ct.DongHo_ID = item.dongho.ID;
                    ct.SoLuong = Convert.ToInt16(item.soLuongTrongGio);
                    ct.DonGia = item.dongho.DonGia - item.dongho.KhuyenMai*item.dongho.DonGia/100;
                    db.DatHang_ChiTiet.Add(ct);
                    var dongho = db.DongHoes.Find(item.dongho.ID);
                    dongho.SoLuong -= item.soLuongTrongGio;
                    db.SaveChanges();
                }

                // Xóa giỏ hàng
                cart.Clear();
                Session["count"] = 0;
                TempData["thongbao"] = "Đặt hàng thành công";
                // Quay về trang chủ
                return RedirectToAction("Index");
            }

            return View(datHang);
        }
    }
}

Views/DongHoes/Category.cshtml
@model IEnumerable<ngay8thang3_Complete.Models.LoaiDH>




@foreach (var item in Model)
{
    <li><a href="@Url.Action("listId","DongHoes", new { id = item.ID })">@item.TenLoai</a></li>
}

Views/DongHoes/Detailsss.cshtml
@model ngay8thang3_Complete.Models.DongHo
@{
    ViewBag.Title = "Detailsss";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detailsss</h2>
@Html.Raw(Model.MoTa)

Views/DongHoes/Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@model PagedList.IPagedList<ngay8thang3_Complete.Models.DongHo>
@{
    ViewBag.Title = "Đồng hồ";
    var ds = new ngay8thang3_Complete.Models.XuatXu();
}

<link href="~/Content/PagedList.css" rel="stylesheet" />

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
    <div class="container">
        <!-- ============================  FILTER TOP  ================================= -->
        <div class="card mb-3">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-2"> Bạn đang ở trang: </div> <!-- col.// -->
                    <nav class="col-md-6">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="~/Home">Trang chủ</a></li>
                            <li class="breadcrumb-item"><a href="~/DongHoes/Index">Danh sách sản phẩm</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Items</li>
                        </ol>
                    </nav> <!-- col.// -->
                    <div class="col-md-4">
                        @using (Html.BeginForm("Index", "DongHoes", FormMethod.Get))
                        {
                            <div class="input-group">
                                <input class="form-control mr-sm-2" type="search" placeholder="Nhập tên sản phẩm" aria-label="Search" name="SearchString">
                                <div class="input-group-append">
                                    <button class="btn btn-primary my-2 my-sm-0" type="submit">Tìm kiếm</button>
                                </div>
                            </div>
                        }
                        @if (Session["search"] != null)
                        {
                            <p style="margin:5px">Từ khóa tìm kiếm: " <span style=""> @Session["search"] </span>"</p>
                        }
                    </div>

                </div> <!-- row.// -->
                <hr>
                <!--<div class="row">
                    <div class="col-md-2">Tìm kiếm theo:</div> <!-- col.// -->
                <!--<div class="col-md-10">
                    <ul class="list-inline">
                        <li class="list-inline-item mr-3 dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">   Thương hiệu </a>
                            <div class="dropdown-menu p-3" style="max-width:400px;">
                                <label class="form-check">
                                    <input type="radio" name="myfilter" class="form-check-input"> Good supplier
                                </label>
                                <label class="form-check">
                                    <input type="radio" name="myfilter" class="form-check-input"> Best supplier
                                </label>
                                <label class="form-check">
                                    <input type="radio" name="myfilter" class="form-check-input"> New supplier
                                </label>
                            </div>-->
                <!-- dropdown-menu.// -->
                <!--</li>
                <li class="list-inline-item mr-3 dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">  Quốc gia </a>
                    <div class="dropdown-menu p-3">
                        <label class="form-check"> 	 <input type="checkbox" class="form-check-input"> China    </label>
                        <label class="form-check">   	 <input type="checkbox" class="form-check-input"> Japan      </label>
                        <label class="form-check">    <input type="checkbox" class="form-check-input"> Uzbekistan  </label>
                        <label class="form-check">  <input type="checkbox" class="form-check-input"> Russia     </label>
                    </div>-->
                <!-- dropdown-menu.// -->
                <!--</li>
                <li class="list-inline-item mr-3 dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Loại đồng hồ</a>
                    <div class="dropdown-menu">
                        <a href="" class="dropdown-item">Anti backterial</a>
                        <a href="" class="dropdown-item">With buttons</a>
                        <a href="" class="dropdown-item">Extra safety</a>
                    </div>
                </li>
                <li class="list-inline-item mr-3"><a href="#">Màu sắc</a></li>
                <li class="list-inline-item mr-3"><a href="#">Kích cỡ</a></li>
                <li class="list-inline-item mr-3">
                    <div class="form-inline">
                        <label class="mr-2">Giá</label>
                        <input class="form-control form-control-sm" placeholder="Min" type="number">
                        <span class="px-2"> - </span>
                        <input class="form-control form-control-sm" placeholder="Max" type="number">
                        <button type="submit" class="btn btn-sm btn-light ml-2">Ok</button>
                    </div>
                </li>
                <li class="list-inline-item mr-3">
                    <label class="custom-control mt-1 custom-checkbox">-->
                @*<input type="checkbox" class="custom-control-input">
                    <div class="custom-control-label">
                        <p> Ready to ship</p>
                    </div>*@
                <!--</label>
                        </li>
                    </ul>
                </div>-->
                <!-- col.// -->
                <!--</div>--> <!-- row.// -->
                <div class="row">

                </div>
            </div> <!-- card-body .// -->
        </div> <!-- card.// -->
        <!-- ============================ FILTER TOP END.// ================================= -->

        <header class="mb-3">
            <div class="form-inline">
                <strong class="mr-md-auto">WATCH LUXURY STORE</strong>
                <select class="mr-2 form-control">
                    <option>Latest items</option>
                    <option>Trending</option>
                    <option>Most Popular</option>
                    <option>Cheapest</option>
                </select>
                <div class="btn-group">
                    <a href="~/DongHoes/Index" class="btn btn-light active" data-toggle="tooltip" title="List view">
                        <i class="fa fa-bars"></i>
                    </a>

                    <a href="~/DongHoes/Index2" class="btn btn-light" data-toggle="tooltip" title="Grid view">
                        <i class="fa fa-th"></i>
                    </a>
                </div>
            </div>
        </header><!-- sect-heading -->

        <div class="row">
            @if (Model.Count() <= 0)
            {
                <span class="alert alert-danger">Hiện chưa có sản phẩm!</span>
            }
            @foreach (var item in Model)
            {
                <div class="col-md-3">

                    <figure class="card card-product-grid">

                        <a href="~/DongHoes/Details/@item.ID" class="img-wrap">
                            @if (item.KhuyenMai != 0)
                            {
                                <span class="badge badge-danger"> @item.KhuyenMai % </span>
                            }
                            <img src="~/@item.HinhAnhDH">
                        </a> <!-- img-wrap.// -->
                        <figcaption class="info-wrap">
                            <a href="~/DongHoes/Details?id=@item.ID" style="height:45px" class="title mb-2">@item.TenDongHo</a>
                            <div class="price-wrap">
                                <span class="price">@string.Format("{0:N0}", item.DonGia)  </span>
                                <small class="text-muted">/per item</small>
                            </div> <!-- price-wrap.// -->

                            <p class="mb-2">@item.SoLuong  <small class="text-muted">(Min Order)</small></p>



                            <hr>

                            <p class="mb-3">
                                <span class="tag"> <i class="fa fa-check"></i> Verified</span>
                                <span class="tag"> @item.HanBaoHanh </span>

                                <span class="tag">@Html.DisplayFor(modelItem => item.ChatLieu.TenChatLieu)</span>
                                <br />
                                <span class="tag">@Html.DisplayFor(modelItem => item.XuatXu.TenQG)</span>
                            </p>

                            <label class="custom-control mb-3 custom-checkbox">
                                <input type="checkbox" class="custom-control-input">
                                <div class="custom-control-label">
                                    <span>Add to compare</span>
                                </div>
                            </label>

                            <a href="@Url.Action("ThemVaoGio", "ShoppingCard", new { maSP = item.ID })" class="btn btn-outline-primary"> <i class="fa fa-shopping-cart"></i> Giỏ hàng </a>
                            <a href="#" class="btn btn-light"><i class="fa fa-heart"></i> Thích </a>

                        </figcaption>



                    </figure>

                </div> <!-- col.// -->
            }

        </div>
        <!-- row end.// -->


        <nav class="mb-4" aria-label="Page navigation sample">
            <ul class="pagination">
                @*<li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                    <li class="page-item active"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item"><a class="page-link" href="#">4</a></li>
                    <li class="page-item"><a class="page-link" href="#">5</a></li>
                    <li class="page-item"><a class="page-link" href="#">Next</a></li>*@
                Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                @Html.PagedListPager(Model, page => Url.Action("Index",
                new { page, currentFilter = ViewBag.CurrentFilter }))

            </ul>
        </nav>


        <div class="box text-center">
            <p>Did you find what you were looking for？</p>
            <a href="" class="btn btn-light">Yes</a>
            <a href="" class="btn btn-light">No</a>
        </div>

    </div> <!-- container .//  -->
</section>

Views/DongHoes/ListId.cshtml
@model IEnumerable<ngay8thang3_Complete.Models.DongHo>


@{

    if(Model.Count() > 0)
    {
        ViewBag.Title = Model.First().LoaiDH.TenLoai;
    }
    else
    {
        ViewBag.title = "Hiện chưa có sản phẩm nào";
    }



}
<section class="padding-bottom-sm">

    <header class="section-heading heading-line">
        <h4 class="title-section text-uppercase">@ViewBag.Title</h4>
    </header>

    <div class="row row-sm">
        @if (Model.Count() > 0)
        {


            foreach (var item in Model)
            {
                <div class="col-xl-2 col-lg-3 col-md-4 col-6">
                    <div href="#" class="card card-sm card-product-grid">
                        <a href="~/DongHoes/Details?id=@item.ID" class="img-wrap"> <img src="~/@item.HinhAnhDH"> </a>
                        <figcaption class="info-wrap">
                            <a style="height:45px" href="~/DongHoes/Details?id=@item.ID" class="title">@item.TenDongHo</a>
                            <div class="price mt-1">@string.Format("{0:N0}", item.DonGia)</div> <!-- price-wrap.// -->
                            <div style="display:flex; justify-content:space-evenly">
                                @if (Session["iduser"] != null)
                                {
                                    <a href="@Url.Action("ThemVaoGio","ShoppingCard",new { maSP = item.ID })" class="btn btn-outline-primary"> <i class="fa fa-shopping-cart"></i> Giỏ hàng </a>
                                    <a href="#" class="btn btn-light"><i class="fa fa-heart"></i> Thích </a>
                                }
                                else
                                {
                                    <a href="~/KhachHangs/Index" class="btn btn-outline-primary"> <i class="fa fa-shopping-cart"></i> Giỏ hàng </a>
                                    <a href="~/KhachHangs/Index" class="btn btn-light"><i class="fa fa-heart"></i> Thích </a>
                                }


                            </div>
                            
                        </figcaption>
                    </div>
                </div>
            }
        }
        else
        {
            <div class="col-xl-2 col-lg-3 col-md-4 col-6">
                <div href="#" class="card card-sm card-product-grid">
                    <span>  Hiện chưa có sản phẩm! xin vui lòng quay lại sau!</span>
                </div>
            </div>
        }
        <!-- col.// -->

    </div> <!-- row.// -->
</section>

Views/DongHoes/ThuongHieu.cshtml
@model IEnumerable<ngay8thang3_Complete.Models.ThuongHieu>

@foreach (var item in Model)
{
    <li><a href="@Url.Action("list_th","DongHoes", new { id = item.ID })" >@item.TenThuongHieu</a></li>
}
        

Views/DongHoes/_KhuyenMai.cshtml

@model IEnumerable<ngay8thang3_Complete.Models.DongHo>

@foreach (var item in Model.Take(5))
{
    <div class="col-md col-6">
        <figure class="card-product-grid card-sm">
            <a href="~/DongHoes/Details?id=@item.ID" class="img-wrap">
                <img src="~/@item.HinhAnhDH">
            </a>
            <div class="text-wrap p-3">
                <a style="height:45px" href="~/DongHoes/Details?id=@item.ID" class="title">@item.TenDongHo</a>
                <span class="badge badge-danger"> @item.KhuyenMai %</span>
            </div>
        </figure>
    </div>
}