Admin/Controllers/DongHoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using ngay8thang3_Complete.Models;
using PagedList;

namespace ngay8thang3_Complete.Areas.Admin.Controllers
{
    public class DongHoController : Controller
    {
        private MyShopDbContext db = new MyShopDbContext();

        // GET: Admin/DongHo
        public ActionResult Index()
        {
            if (Session["fullnameAdmin"] == null)
            {
                return RedirectToAction("DangNhap", "Home");
            }
            else
            {
                if (TempData["result"] != null)
                {
                    ViewBag.SuccessMsg = TempData["result"];
                }
                var dongHoes = db.DongHoes.Include(d => d.ChatLieu).Include(d => d.LoaiDH).Include(d => d.ThuongHieu).Include(d => d.XuatXu);
                return View(dongHoes.ToList());
            }

        }
        //dùng tay để phân trang, tìm kiếm và sắp xếp
        //public ActionResult Index(string currentFilter, string SearchString, int? page)
        //{
        //    var dongho = new List<DongHo>();
        //    if (SearchString != null)
        //    {
        //        page = 1;
        //    }
        //    else
        //    {
        //        SearchString = currentFilter;
        //    }
        //    if (!string.IsNullOrEmpty(SearchString))
        //    {
        //        //lấy ds sản phẩm theo từ khóa tìm kiếm
        //        dongho = db.DongHoes.Where(n => n.TenDongHo.Contains(SearchString)).ToList();
        //    }
        //    else
        //    {
        //        //lay all sån phâm trong bång product
        //        dongho = db.DongHoes.ToList();
        //    }
        //    ViewBag.CurrentFilter = SearchString;
        //    //số lượng item của 1 trang = 4
        //    int pageSize = 5;
        //    int pageNumber = (page ?? 1);
        //    if (dongho.Count<1)
        //    {
        //        ViewBag.thongbao = "Hiện tại không có sản phẩm nào";
        //    }
        //    //sắp xếp theo id sản phẩm,sp mới đưa lên đầu
        //    dongho = dongho.OrderByDescending(n => n.ID).ToList();
        //    return View(dongho.ToPagedList(pageNumber, pageSize));

        //}
        public ActionResult index2()
        {

            return View(db.DongHoes.ToList());
        }
        // GET: Admin/DongHo/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DongHo dongHo = db.DongHoes.Find(id);
            if (dongHo == null)
            {
                return HttpNotFound();
            }
            return View(dongHo);
        }

        // GET: Admin/DongHo/Create
        public ActionResult Create()
        {
            ViewBag.ChatLieu_ID = new SelectList(db.ChatLieux, "ID", "TenChatLieu");
            ViewBag.TenLoai_ID = new SelectList(db.LoaiDHs, "ID", "TenLoai");
            ViewBag.ThuongHieu_ID = new SelectList(db.ThuongHieux, "ID", "TenThuongHieu");
            ViewBag.XuatXu_ID = new SelectList(db.XuatXus, "ID", "TenQG");
            return View();
        }

        // POST: Admin/DongHo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "ID,ThuongHieu_ID,TenLoai_ID,ChatLieu_ID,XuatXu_ID,TenDongHo,MauSac,HanBaoHanh,DonGia,SoLuong,HinhAnhDH,MoTaNgan,Đaciem,MoTa,KhuyenMai")] DongHo dongHo)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    dongHo.HinhAnhDH = "Storage/";
                    var f = Request.Files["ImageFile"];
                    if (f != null && f.ContentLength > 0)
                    {
                        string filename = Path.GetFileName(f.FileName);
                        string upload = Server.MapPath("~/Storage/" + filename);
                        f.SaveAs(upload);
                        dongHo.HinhAnhDH += filename;
                    }
                    db.DongHoes.Add(dongHo);
                    db.SaveChanges();
                    TempData["result"] = "Thêm mới thành công";
                   
                }
                
                TempData["result"] = "thêm mới Thành công";
                return RedirectToAction("Index");
               

            }
            catch (Exception)
            {
                ViewBag.ChatLieu_ID = new SelectList(db.ChatLieux, "ID", "TenChatLieu", dongHo.ChatLieu_ID);
                ViewBag.TenLoai_ID = new SelectList(db.LoaiDHs, "ID", "TenLoai", dongHo.TenLoai_ID);
                ViewBag.ThuongHieu_ID = new SelectList(db.ThuongHieux, "ID", "TenThuongHieu", dongHo.ThuongHieu_ID);
                ViewBag.XuatXu_ID = new SelectList(db.XuatXus, "ID", "TenQG", dongHo.XuatXu_ID);
                return View(dongHo);

            }



        }

        // GET: Admin/DongHo/Edit/5

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DongHo dongHo = db.DongHoes.Find(id);
            if (dongHo == null)
            {
                return HttpNotFound();
            }
            ViewBag.ChatLieu_ID = new SelectList(db.ChatLieux, "ID", "TenChatLieu", dongHo.ChatLieu_ID);
            ViewBag.TenLoai_ID = new SelectList(db.LoaiDHs, "ID", "TenLoai", dongHo.TenLoai_ID);
            ViewBag.ThuongHieu_ID = new SelectList(db.ThuongHieux, "ID", "TenThuongHieu", dongHo.ThuongHieu_ID);
            ViewBag.XuatXu_ID = new SelectList(db.XuatXus, "ID", "TenQG", dongHo.XuatXu_ID);
            return View(dongHo);
        }

        // POST: Admin/DongHo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "ID,ThuongHieu_ID,TenLoai_ID,ChatLieu_ID,XuatXu_ID,TenDongHo,MauSac,HanBaoHanh,DonGia,SoLuong,HinhAnhDH,MoTaNgan,Đaciem,MoTa,KhuyenMai,GiaNhap")] DongHo dongHo)
        {
            if (ModelState.IsValid)
            {
                //dongHo.HinhAnhDH = "Storage/";
                //var f = Request.Files["HinhAnhDH"];
                //if (f != null && f.ContentLength > 0)
                //{
                //    string filename = Path.GetFileName(f.FileName);
                //    string upload = Server.MapPath("~/Storage/" + filename);
                //    f.SaveAs(upload);
                //    dongHo.HinhAnhDH += filename;
                //}
                db.Entry(dongHo).State = EntityState.Modified;
                db.SaveChanges();
                TempData["result"] = "Cập nhật thành công";
                return RedirectToAction("Index");
            }
            ViewBag.ChatLieu_ID = new SelectList(db.ChatLieux, "ID", "TenChatLieu", dongHo.ChatLieu_ID);
            ViewBag.TenLoai_ID = new SelectList(db.LoaiDHs, "ID", "TenLoai", dongHo.TenLoai_ID);
            ViewBag.ThuongHieu_ID = new SelectList(db.ThuongHieux, "ID", "TenThuongHieu", dongHo.ThuongHieu_ID);
            ViewBag.XuatXu_ID = new SelectList(db.XuatXus, "ID", "TenQG", dongHo.XuatXu_ID);
            return View(dongHo);
        }

        // GET: Admin/DongHo/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DongHo dongHo = db.DongHoes.Find(id);
            if (dongHo == null)
            {
                return HttpNotFound();
            }
            return View(dongHo);
        }

        // POST: Admin/DongHo/Delete/5

        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                DongHo dongHo = db.DongHoes.Find(id);
                db.DongHoes.Remove(dongHo);
                db.SaveChanges();
                TempData["result"] = "Xóa thành công";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {

                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

        }
        //Khuyễn mại

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Admin/Views/DongHo/Create.cshtml
@model ngay8thang3_Complete.Models.DongHo

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div style="margin:50px; width:800px">


    <h2>Thêm mới sản phẩm</h2>

    @using (Html.BeginForm("Create", "DongHo", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Đồng hồ</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ThuongHieu_ID, "ThuongHieu_ID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ThuongHieu_ID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ThuongHieu_ID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TenLoai_ID, "TenLoai_ID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("TenLoai_ID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TenLoai_ID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ChatLieu_ID, "ChatLieu_ID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ChatLieu_ID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ChatLieu_ID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.XuatXu_ID, "XuatXu_ID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("XuatXu_ID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.XuatXu_ID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TenDongHo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TenDongHo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TenDongHo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MauSac, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MauSac, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MauSac, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HanBaoHanh, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.HanBaoHanh, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HanBaoHanh, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HinhAnhDH, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <img id="output" class="img-rounded" alt="ảnh" width="180" height="200" src="" />
                    <p><label for="ufile" style="cursor: pointer;">Chọn file ảnh</label></p>
                    <input type="file" name="ImageFile" id="ufile" style="display:none;" onchange="loadFile(event)" />
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.MoTaNgan, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MoTaNgan, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MoTaNgan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Đaciem, htmlAttributes: new { @class = "control-label col-md-2" })
                <textarea class="col-md-10" id="noidung" name="Đaciem">
                   
                </textarea>

                @Html.ValidationMessageFor(model => model.Đaciem, "", new { @class = "text-danger" })

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.KhuyenMai, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.KhuyenMai, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.KhuyenMai, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input id="btnSubmit" type="submit" value="Thêm mới" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        <a href="javascript: history.back()" class="btn btn-light"> &laquo Quay lại</a>
    </div>

</div>
@section scripts{
    <script>
        var loadFile = function (event) {
            var image = document.getElementById('output');
            image.src = URL.createObjectURL(event.target.files[0]);
        };
        CKEDITOR.replace('noidung');
    </script>
    <script>
        $(document).ready(function () {
            $('#btnSubmit').click(function () {
                
            })
        })
    </script>
}

Admin/Views/DongHo/Delete.cshtml
@model ngay8thang3_Complete.Models.DongHo

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DongHo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ChatLieu.TenChatLieu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChatLieu.TenChatLieu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiDH.TenLoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiDH.TenLoai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThuongHieu.TenThuongHieu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThuongHieu.TenThuongHieu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.XuatXu.TenQG)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.XuatXu.TenQG)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenDongHo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenDongHo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MauSac)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MauSac)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HanBaoHanh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HanBaoHanh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonGia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnhDH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhAnhDH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTaNgan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTaNgan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Đaciem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Đaciem)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTaNgan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>
        <dd>
            @Html.DisplayFor(model => model.KhuyenMai)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Delete" class="btn btn-default" /> |
    <a href="javascript: history.back()" class="btn btn-light"> &laquo Quay lại</a>
</div>
    }
</div>

Admin/Views/DongHo/Edit.cshtml
@model ngay8thang3_Complete.Models.DongHo

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var ImagePath = Model.HinhAnhDH;
}

<div style="width:800px; margin:50px">


    @using (Html.BeginForm("Edit", "DongHo", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@Model.TenDongHo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.ThuongHieu_ID, "ThuongHieu_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ThuongHieu_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ThuongHieu_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenLoai_ID, "TenLoai_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TenLoai_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TenLoai_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChatLieu_ID, "ChatLieu_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ChatLieu_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ChatLieu_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.XuatXu_ID, "XuatXu_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("XuatXu_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.XuatXu_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenDongHo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" name="TenDongHo" value="@Model.TenDongHo" class="form-control" />
                @Html.ValidationMessageFor(model => model.TenDongHo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MauSac, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MauSac, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MauSac, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HanBaoHanh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HanBaoHanh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HanBaoHanh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">

            @*<div class="col-md-10">
                <img id="output" class="img-rounded" alt="ảnh" width="180" height="200" src="~/@Url.Content(ImagePath)" />
                <p><label for="ufile" style="cursor: pointer;">Chọn file ảnh</label></p>
                <input type="file" name="HinhAnhDH" id="ufile" style="display:none;" onchange="loadFile(event)" />
            </div>*@
            @Html.LabelFor(model => model.HinhAnhDH, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.HinhAnhDH, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HinhAnhDH, "", new { @class = "text-danger" })

        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.MoTaNgan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTaNgan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTaNgan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Đaciem, htmlAttributes: new { @class = "control-label col-md-2" })
            <textarea class="col-md-10" id="noidung" name="Đaciem">
                    @Model.Đaciem
                </textarea>

            @Html.ValidationMessageFor(model => model.Đaciem, "", new { @class = "text-danger" })

        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.KhuyenMai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KhuyenMai, new { htmlAttributes = new { @class = "form-control" } }) <span>%</span>
                @Html.ValidationMessageFor(model => model.KhuyenMai, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.GiaNhap, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaNhap, new { htmlAttributes = new { @class = "form-control" } }) 
                @Html.ValidationMessageFor(model => model.GiaNhap, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
    }

    <div>
        <a href="javascript: history.back()" class="btn btn-light"> &laquo Quay lại</a>
    </div>
</div>

@section scripts{

    <script>


        CKEDITOR.replace('noidung');


    </script>
}
<script>
    var loadFile = function (event) {
        var image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0]);
    };
</script>