Admin/Controllers/NhanViensController.cs
using ngay8thang3_Complete.Models;
using ngay8thang3_Complete.Models.CommonModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ngay8thang3_Complete.Areas.Admin.Controllers
{
    public class NhanViensController : Controller
    {
        // GET: Admin/NhanViens
        MyShopDbContext db = new MyShopDbContext();
        private string GetMD5(string matKhau)
        {
            MD5 md5 = new MD5CryptoServiceProvider();
            byte[] fromdata = Encoding.UTF8.GetBytes(matKhau);
            byte[] targetData = md5.ComputeHash(fromdata);
            string byte25string = null;
            for (int i = 0; i < targetData.Length; i++)
            {
                byte25string += targetData[i].ToString("x2");
            }
            return byte25string;
        }
        [HttpGet]
        public ActionResult Index()
        {
            if (TempData["resultdn"] != null)
            {
                ViewBag.SuccessMsg = TempData["resultdn"];
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Index(NhanVienModel nhanvien)
        {
            if (ModelState.IsValid)
            {
                string fpass = Models.CommonModel.SHA1.ComputeHash(nhanvien.MatKhau); //mã hóa
                var getUser = db.NhanViens.Where(m => m.TenDangNhap == nhanvien.TenDangNhap).FirstOrDefault();
                if (getUser==null)
                {
                    ViewBag.login = "Tên đăng nhập không tồn tại";
                    return View("Index");
                }
               else if (nhanvien.MatKhau == "123456")
                {
                    Session["idadmin"] = getUser.ID;
                    Session["fullnameAdmin"] = getUser.TenDangNhap;
                    Session["fullnameAd"] = getUser.HoVaTen;
                    Session["quyen"] = getUser.Quyen;
                    TempData["resultdn"] = "Đăng nhập thành công";
                    return RedirectToAction("Index", "Home");

                }
               else if (getUser.MatKhau != fpass)
                {
                    ViewBag.login = "Tên đăng nhập hoặc mật khẩu không chính xác";
                    return View("Index");
                }
                else
                {
                    Session["idadmin"] = getUser.ID;
                    Session["fullnameAdmin"] = getUser.TenDangNhap;
                    Session["fullnameAd"] = getUser.HoVaTen;
                    Session["quyen"] = getUser.Quyen;
                    TempData["resultdn"] = "Đăng nhập thành công";
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                ViewBag.login = "Đăng nhập thất bại";
                return View("Index");
            }

        }
        public ActionResult Logout()
        {
            Session["fullnameAdmin"] = null;
            Session["fullnameAd"] = null;
            return RedirectToAction("DangNhap","Home");
        }
        public ActionResult changePassword()
        {
            return View();
        }
        public ActionResult ListNv()
        {
            if (TempData["result"]!=null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }    
            return View(db.NhanViens.ToList());
        }
        public ActionResult Create()
        {
            return View();

            
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include ="HoVaTen,DienThoai,DiaChi,TenDangNhap,MatKhau,Quyen")]NhanVien nv)
        {
            if(ModelState.IsValid)
            {
                db.NhanViens.Add(nv);
                db.SaveChanges();
                TempData["result"] = "Thêm mới thành công";
                return RedirectToAction("ListNv");
            }
            return View();
        }
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                var x = db.NhanViens.Find(id);
                db.NhanViens.Remove(x);
                db.SaveChanges();
                TempData["result"] = "Đã xóa thành công";
                return RedirectToAction("ListNv");
            }
            catch (Exception)
            {
                TempData["result"] = "Có lỗi xảy ra. hãy thử thực hiện lại";
               return RedirectToAction("ListNv");
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,HoVaTen,DienThoai,DiaChi,TenDangNhap,Quyen")] NhanVien nv)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nv).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
          
            return View(nv);
        }
     
        public ActionResult DoiMatKhau()
        {
            if (TempData["success"]!=null)
            {
                ViewBag.success = TempData["success"];
            }    
                return View();
        } 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DoiMatKhau([Bind(Include = "MatKhau,MatKhauMoi,XacNhanMatKhauMoi")] NhanVienChangePassword nhanVienChangePassword)
        {
            if (ModelState.IsValid)
            {
                int manv = Convert.ToInt32(Session["idadmin"]);
                NhanVien nhanVien = db.NhanViens.Find(manv);
                if (nhanVien == null)
                {
                    return HttpNotFound();
                }
                string mk = Models.CommonModel.SHA1.ComputeHash(nhanVienChangePassword.MatKhau);
                nhanVienChangePassword.MatKhau = mk;
                
                if (nhanVien.MatKhau == nhanVienChangePassword.MatKhau)
                {
                    nhanVienChangePassword.MatKhauMoi = Models.CommonModel.SHA1.ComputeHash(nhanVienChangePassword.MatKhauMoi);
                    nhanVienChangePassword.XacNhanMatKhauMoi = nhanVienChangePassword.MatKhauMoi;

                    nhanVien.MatKhau = nhanVienChangePassword.MatKhauMoi;
                   
                    db.Entry(nhanVien).State = EntityState.Modified;
                    db.SaveChanges();
                    TempData["success"] = "Đổi mật khẩu thành công! hãy đăng nhập lại";
                    return RedirectToAction("Logout");
                }
                else
                {
                    ViewBag.error = "Mật khẩu cũ không đúng !!!";
                    return View();
                }

            }
            return View(nhanVienChangePassword);
        }

    }
}

Admin/Views/NhanViens/Create.cshtml
@model ngay8thang3_Complete.Models.NhanVien

@{
    ViewBag.Title = "Tài khoản nhân viên";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div style="margin:10px">



    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Thêm tài khoản nhân viên</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.HoVaTen, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.HoVaTen, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HoVaTen, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DienThoai, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DienThoai, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TenDangNhap, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TenDangNhap, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TenDangNhap, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Quyen, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Quyen)
                        @Html.ValidationMessageFor(model => model.Quyen, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Thêm mới" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        <a href="javascript: history.back()" class="btn btn-light"> &laquo Quay lại</a>
    </div>
</div>

Admin/Views/NhanViens/DoiMatKhau.cshtml
@model ngay8thang3_Complete.Models.CommonModel.NhanVienChangePassword
@{
    ViewBag.Title = "Đổi mật khẩu nhân viên";
}

<div class="card mt-3">
    <h5 class="card-header">@ViewBag.Title</h5>
    <div class="card-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                @Html.LabelFor(model => model.MatKhau)
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
                @if (ViewBag.error != null)
                {
                    <span class="badge badge-danger mt-2">@ViewBag.error</span>
                }
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MatKhauMoi)
                @Html.EditorFor(model => model.MatKhauMoi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhauMoi, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.XacNhanMatKhauMoi)
                @Html.EditorFor(model => model.XacNhanMatKhauMoi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.XacNhanMatKhauMoi, "", new { @class = "text-danger" })
            </div>


            <div class="form-group mb-0">
                <input type="submit" value="Xác nhận " class="btn btn-success" /> hoặc @Html.ActionLink("Quay về trang chủ", "Index", "Home")
            </div>
        }
    </div>
</div>

@section Scripts {


    @Scripts.Render("~/bundles/jqueryval")
 
}

Admin/Views/NhanViens/Edit.cshtml
@model ngay8thang3_Complete.Models.NhanVien

@{
    ViewBag.Title = "Sửa thông tin";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sửa thông tin nhân viên</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.HoVaTen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoVaTen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoVaTen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DienThoai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DienThoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenDangNhap, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenDangNhap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenDangNhap, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Quyen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Quyen)
                    @Html.ValidationMessageFor(model => model.Quyen, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

Admin/Views/NhanViens/Index.cshtml
@model ngay8thang3_Complete.Models.CommonModel.NhanVienModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<style>
    .form-group {
        padding: 5px;
        
    }

    .form-label {
        width: 150px;
        margin: 0;
        margin: auto;
        font-weight: normal !important;
    }

    .btn-primary {
        margin: 10px 150px;
    }
</style>
@if (ViewBag.success != null)
{
    <div id="AlertBox" class="alert alert-success">
        @ViewBag.success
    </div>
}
<h3 style="text-align:center; padding:50px">Đăng nhập tài khoản admin</h3>
<div style="display: flex; margin: 0 150px; margin: 0 300px; padding: 40px;" class="border border-success">
    <div class="mb-3" style="margin: auto">
        @using (Html.BeginForm("Index", "NhanViens", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                <label for="exampleInputEmail1" class="form-label">Tên tài khoản</label>
                @Html.EditorFor(model => model.TenDangNhap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenDangNhap, "", new { @class = "text-danger" })
            </div> <!-- form-group// -->
            <div class="form-group">
                <label for="exampleInputEmail1" class="form-label">Mật khẩu</label>
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div> <!-- form-group// -->
            <div class="form-group">
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="remember" name="remember">
                    <label class="form-check-label" for="remember">Remember me</label>
                </div>
            </div>
            <p style="color:red">@ViewBag.login</p>
            <button type="submit" class="btn btn-primary">Đăng nhập</button>

        }
    </div>
</div>
@section scripts{
    <script>
        $(function () {
            $('#AlertBox').removeClass('hide');
            $('#AlertBox').delay(2000).slideUp(500);
        });
    </script>
    }

Admin/Views/NhanViens/ListNv.cshtml
@model IEnumerable<ngay8thang3_Complete.Models.NhanVien>

@{
    ViewBag.Title = "Nhân viên";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
<link href="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js" rel="stylesheet" />


<div class="card mt-3">
    <h5 class="card-header">@ViewBag.Title</h5>
    <div class="card-body">
        @if (ViewBag.SuccessMsg != null)
        {
            <div id="AlertBox" class="alert alert-success">
                <p>@ViewBag.SuccessMsg</p>
            </div>
        }
        <p>
            <a class="btn btn-success" href="@Url.Action("Create")" role="button">Thêm mới</a>
        </p>
        <table id="Panigation" class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th width="5%">#</th>
                    <th>
                        @Html.DisplayNameFor(model => model.HoVaTen)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DienThoai)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DiaChi)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TenDangNhap)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.Quyen)
                    </th>
                    <th width="5%">Sửa</th>
                    <th width="5%">Xóa</th>
                </tr>
            </thead>
            <tbody>
                @{ int stt = 1; }
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@stt</td>
                        <td>
                            @Html.DisplayFor(modelItem => item.HoVaTen)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DienThoai)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DiaChi)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TenDangNhap)
                        </td>

                        <td>
                            @if (item.Quyen == true)
                            {
                                <span class="badge badge-danger">Quản lý</span>
                            }
                            else
                            {
                                <span class="badge badge-warning">Nhân viên</span>
                            }
                        </td>
                        <td class="text-center">
                            <a href="~/Admin/NhanViens/Edit?id=@item.ID"><i class="fas fa-edit"></i></a>
                        </td>
                        <td class="text-center">
                            <a href="~/Admin/NhanViens/DeleteConfirmed?id=@item.ID" onclick="return confirm('Bạn muốn xóa Tài khoản này không');"><i class="fas fa-trash-alt text-danger"></i></a>
                        </td>
                    </tr>
                    stt++;
                }
            </tbody>
        </table>
        <a href="javascript: history.back()" class="btn btn-light"> &laquo Quay lại</a>
    </div>
</div>

@section Scripts{
    <script>

        $(function () {
            $('#AlertBox').removeClass('hide');
            $('#AlertBox').delay(2000).slideUp(500);
        });

        $(document).ready(function () {
            $('#Panigation').DataTable({
                "language": {
                    "lengthMenu": "Số dòng _MENU_  trên trang ",
                    "zeroRecords": "Không tìm thấy!!!",
                    "info": "Trang  _PAGE_ của _PAGES_",
                    "infoEmpty": "Không có sẵn dữ liệu",
                    "infoFiltered": "(được lọc từ tổng _MAX_  dữ liệu)"
                }
            });
        });
    </script>
    <script>
        //function confirm() {
        //    var result = confirm();
        //    if (result == true) {
        //        return true;
        //    }

        //    else {
        //        return false;
        //    }
        //}
        function confirm() {
            var result = confirm();
            if (result == true) {
                return true;
            } else {
                return false;
            }
    </script>

}